name: Build MamaHala

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Required Tools
      run: |
        brew install ldid dpkg

    - name: Setup Theos and SDKs
      run: |
        git clone --recursive https://github.com/theos/theos.git $HOME/theos
        git clone --depth=1 https://github.com/theos/sdks.git $HOME/theos/sdks
        echo "THEOS=$HOME/theos" >> $GITHUB_ENV
        echo "$HOME/theos/bin" >> $GITHUB_PATH

    - name: Build Tweak
      run: |
        make package

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MamaHala-Dylib
        path: packages/*.deb
