name: Build MamaHala

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Theos
      uses: unforgiven-dev/install-theos@master

    - name: Build Tweak
      run: |
        make package

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MamaHala-Dylib
        path: packages/*.deb
