name: Build Mod Menu

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Theos Locally
        run: |
          git clone --recursive https://github.com/theos/theos.git $HOME/theos

      - name: Compile mod.xm directly
        run: |
          export THEOS=$HOME/theos
          export PATH="$THEOS/bin:$PATH"
          logos.pl mod.xm > mod.mm
          clang++ -dynamiclib -arch arm64 -isysroot $(xcrun --sdk iphoneos --show-sdk-path) -F$(xcrun --sdk iphoneos --show-sdk-path)/System/Library/Frameworks -framework UIKit -framework Foundation mod.mm -o MamaHala.dylib

      - name: Upload dylib artifact
        uses: actions/upload-artifact@v3
        with:
          name: MamaHala
          path: MamaHala.dylib
